export const DUMMY_REALTIME_CASES = [
  { 
    id: 'dummy-1', 
    problem_type: 'food', 
    location: 'Dharavi Sector 3, Mumbai', 
    priority: 'high', 
    status: 'pending', 
    source: 'form', 
    people_affected: 45, 
    urgency: 5, 
    description: 'Extreme food shortage reported via community center form.', 
    createdAt: Date.now() - 3600000, 
    _dbInstance: 'form',
    lat: '19.0443',
    lng: '72.8550'
  },
  { 
    id: 'dummy-2', 
    problem_type: 'medical', 
    location: 'Bandra West, Mumbai', 
    priority: 'medium', 
    status: 'inprogress', 
    source: 'form', 
    people_affected: 2, 
    urgency: 4, 
    description: 'Medical assistance required for elderly residents.', 
    createdAt: Date.now() - 7200000, 
    _dbInstance: 'form',
    lat: '19.0596',
    lng: '72.8295'
  },
  { 
    id: 'dummy-3', 
    problem_type: 'water', 
    location: 'Thane West, Maharashtra', 
    priority: 'low', 
    status: 'completed', 
    source: 'form', 
    people_affected: 150, 
    urgency: 2, 
    description: 'Pipeline burst reported; maintenance requested.', 
    createdAt: Date.now() - 86400000, 
    _dbInstance: 'form',
    lat: '19.2183',
    lng: '72.9781'
  },
  { 
    id: 'dummy-4', 
    problem_type: 'shelter', 
    location: 'Dadar East, Mumbai', 
    priority: 'high', 
    status: 'pending', 
    source: 'whatsapp', 
    people_affected: 12, 
    urgency: 5, 
    description: 'Emergency shelter needed for family after building collapse.', 
    createdAt: Date.now() - 1800000, 
    _dbInstance: 'form',
    lat: '19.0178',
    lng: '72.8478'
  },
  { 
    id: 'dummy-5', 
    problem_type: 'disaster', 
    location: 'Chembur, Mumbai', 
    priority: 'high', 
    status: 'inprogress', 
    source: 'whatsapp', 
    people_affected: 30, 
    urgency: 5, 
    description: 'Localized flooding reported via WhatsApp bot.', 
    createdAt: Date.now() - 5400000, 
    _dbInstance: 'form',
    lat: '19.0522',
    lng: '72.8995'
  },
  { 
    id: 'dummy-6', 
    problem_type: 'education', 
    location: 'Govandi, Mumbai', 
    priority: 'low', 
    status: 'pending', 
    source: 'whatsapp', 
    people_affected: 25, 
    urgency: 1, 
    description: 'Request for school supplies and books.', 
    createdAt: Date.now() - 172800000, 
    _dbInstance: 'form',
    lat: '19.0560',
    lng: '72.9322'
  }
];
